### ISSUE TITLE
Can you give us permission to fork this project and continue this project?

### ISSUE THREAD

**Issue by piraz** [puentesarrin/wtforms-tornado#3]
It seems like there is no development but some people are using this project. Can you give us ownership or permission to fork this project?

There is no license to this project also, so we can't even fork the project safely. It would be great to know what kind of license this project has.

**Comment by piraz** [comment]
It seems the project is under Apache License, Version 2.0.

**Comment by puentesarrin** [comment]
Hi @piraz, you have answered yourself :)

**Comment by piraz** [comment]
Going with the name of tornado-wtfroms on pypi. Thank you very much @puentesarrin.

**Comment by puentesarrin** [comment]
I answered about the license only, btw. I'll continue working this library in my spare time, as you maybe already noticed it I introduced changes for latest dependencies yesterday.
